# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KNU_CSE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KNU_CSE

  target 'KNU_CSETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KNU_CSEUITests' do
    # Pods for testing
  end
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'M13Checkbox'
  pod 'NVActivityIndicatorView'
  pod 'DropDown'
  pod 'BTNavigationDropdownMenu'
end
